import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Vercel Secret Sync</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Woopee! the below secrets were imported using{' '}
          <a href="https://github.com/simonireilly/aws-cdk-utils">CDK-Utils</a>
        </h1>

        <p className={styles.description}>Get started by editing</p>
        <pre>secret: {process.env.NEXT_PUBLIC_COGNITO_USER_POOL_ID}</pre>
        <pre>timestamp: {process.env.NEXT_PUBLIC_UPDATED_TIMESTAMP_TEST}</pre>
        <p>Test git changes</p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
