#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# yarn test
yarn embed
yarn syncpack format
# Allow peer dependencies to be unique
yarn syncpack fix-mismatches --prod --dev
# Allow peer dependencies to be unique
yarn syncpack set-semver-ranges --prod --dev
