on:
  pull_request:
    branches: [main]

name: Lint, Build, Test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: preview

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node version
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2

      - run: pnpm install

      - run: pnpm build

      - run: pnpm test
