on:
  pull_request:
    branches: [main]

name: Lint, Build, Test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: preview

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup yarn cache
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      - run: yarn install
