on:
  pull_request:
    branches: [main]

name: Lint, Build, Test

jobs:
  pre-release-check:
    name: Check code is releasable
    runs-on: ubuntu-latest
    environment: preview

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install node version
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      - name: Configure publishing user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

      - run: yarn install

      - run: yarn lerna bootstrap

      - name: Configure authentication for NPM
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Prerelease Check
        run: yarn lerna publish prerelease --no-push --no-git-tag-version --dist-tag canary --yes
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    environment: preview

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node version
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      - run: yarn install --frozen-lockfile

      - run: yarn build

      - run: yarn test
