on:
  push:
    branches: [main]

name: Automate Canary Publishing

jobs:
  publish-canary:
    name: Publish Canary of package to NPM registry; with Git Release Tags
    runs-on: ubuntu-latest
    environment: preview

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install node version
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      - run: yarn install --frozen-lockfile

      - run: yarn build

      - run: yarn test

      - name: Configure publishing user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

      - name: Publish canary version with automation token
        run: yarn lerna publish prerelease --dist-tag canary --no-verify-access --yes
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
